language: python

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - python run_tests.py

# Push the results back to codecov
after_success:
  - codecov